// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzeiwmtinjdhroyzcumi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6ZWl3bXRpbmpkaHJveXpjdW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzQxOTMsImV4cCI6MjA1NTgxMDE5M30.8gRrvxCfXb5jvy0SkhwS_Mt1Y3TQGJXk4823AW-zZjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);